CREATE TABLE IF NOT EXISTS users
(
  id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name   varchar(255) NOT NULL,
  email  varchar(64) NOT NULL,
  CONSTRAINT UNIQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL,
  CONSTRAINT UNIQ_CATEGORY_NAME UNIQUE (name)
);
